language: node_js
node_js:
  - '9.11.2'
script:
  - yarn test
  - yarn build
  - yarn size
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  yarn: true
  directories:
    - node_modules
after_success: yarn codecov
deploy:
  provider: npm
  skip_cleanup: true
  email: 'laheen@gmail.com'
  api_key: $NPM_KEY
  on:
    tags: true
